// <auto-generated />
using System;
using LevelHabit.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LevelHabit.Api.Migrations
{
    [DbContext(typeof(LevelHabitDbContext))]
    [Migration("20260715140923_NormalizeDatabaseObjectNamesV2")]
    partial class NormalizeDatabaseObjectNamesV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LevelHabit.Api.Domain.Achievement", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("rule");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("Target")
                        .HasColumnType("integer")
                        .HasColumnName("target");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.HasKey("Key");

                    b.HasIndex("SortOrder");

                    b.ToTable("achievements", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "first-step",
                            Description = "Complete your first habit.",
                            Rule = "total-completions",
                            SortOrder = 10,
                            Target = 1,
                            Title = "First Step"
                        },
                        new
                        {
                            Key = "getting-started",
                            Description = "Complete 5 habits total.",
                            Rule = "total-completions",
                            SortOrder = 20,
                            Target = 5,
                            Title = "Getting Started"
                        },
                        new
                        {
                            Key = "dedicated",
                            Description = "Complete 25 habits total.",
                            Rule = "total-completions",
                            SortOrder = 30,
                            Target = 25,
                            Title = "Dedicated"
                        },
                        new
                        {
                            Key = "level-up",
                            Description = "Reach level 2.",
                            Rule = "level",
                            SortOrder = 40,
                            Target = 2,
                            Title = "Level Up"
                        },
                        new
                        {
                            Key = "progress-rising",
                            Description = "Reach level 5.",
                            Rule = "level",
                            SortOrder = 50,
                            Target = 5,
                            Title = "Progress Rising"
                        },
                        new
                        {
                            Key = "on-fire",
                            Description = "Reach a 3-day streak on any habit.",
                            Rule = "best-habit-streak",
                            SortOrder = 60,
                            Target = 3,
                            Title = "On Fire"
                        },
                        new
                        {
                            Key = "unstoppable",
                            Description = "Reach a 7-day streak on any habit.",
                            Rule = "best-habit-streak",
                            SortOrder = 70,
                            Target = 7,
                            Title = "Unstoppable"
                        },
                        new
                        {
                            Key = "hard-mode",
                            Description = "Complete a hard habit.",
                            Rule = "hard-completion",
                            SortOrder = 80,
                            Target = 1,
                            Title = "Hard Mode"
                        },
                        new
                        {
                            Key = "balanced-progress",
                            Description = "Complete habits in at least 3 different categories.",
                            Rule = "completed-categories",
                            SortOrder = 90,
                            Target = 3,
                            Title = "Balanced Progress"
                        });
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.AuthToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("purpose");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Purpose");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("auth_tokens", (string)null);
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("frequency");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsArchived");

                    b.ToTable("habits", (string)null);
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.HabitCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateOnly>("CompletionDateUtc")
                        .HasColumnType("date")
                        .HasColumnName("completion_date_utc");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uuid")
                        .HasColumnName("habit_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("XpAwarded")
                        .HasColumnType("integer")
                        .HasColumnName("xp_awarded");

                    b.HasKey("Id");

                    b.HasIndex("HabitId");

                    b.HasIndex("UserId", "HabitId", "CompletionDateUtc")
                        .IsUnique();

                    b.ToTable("habit_completions", (string)null);
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.HabitReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DaysOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("days_of_week");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uuid")
                        .HasColumnName("habit_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTimeOffset?>("LastTriggeredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_triggered_at_utc");

                    b.Property<DateTimeOffset?>("NextTriggerAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_trigger_at_utc");

                    b.Property<TimeOnly>("TimeOfDay")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_of_day");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("HabitId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("IsEnabled", "NextTriggerAtUtc");

                    b.ToTable("habit_reminders", (string)null);
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeduplicationKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("deduplication_key");

                    b.Property<Guid?>("HabitId")
                        .HasColumnType("uuid")
                        .HasColumnName("habit_id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at_utc");

                    b.Property<string>("ReferenceUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reference_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("HabitId");

                    b.HasIndex("UserId", "DeduplicationKey")
                        .IsUnique()
                        .HasFilter("deduplication_key IS NOT NULL");

                    b.HasIndex("UserId", "IsRead", "CreatedAtUtc");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.ProgressProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer")
                        .HasColumnName("current_streak");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("display_name");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("TotalXp")
                        .HasColumnType("integer")
                        .HasColumnName("total_xp");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("progress_profiles", (string)null);
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAtUtc");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_confirmed");

                    b.Property<DateTimeOffset?>("EmailConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_confirmed_at_utc");

                    b.Property<DateTimeOffset?>("EmailVerificationCodeExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verification_code_expires_at_utc");

                    b.Property<string>("EmailVerificationCodeHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("email_verification_code_hash");

                    b.Property<DateTimeOffset?>("EmailVerificationCodeLastSentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verification_code_last_sent_at_utc");

                    b.Property<int>("EmailVerificationFailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("email_verification_failed_attempts");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.UserAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AchievementKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("achievement_key");

                    b.Property<DateTimeOffset>("UnlockedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AchievementKey");

                    b.HasIndex("UserId", "AchievementKey")
                        .IsUnique();

                    b.ToTable("user_achievements", (string)null);
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.AuthToken", b =>
                {
                    b.HasOne("LevelHabit.Api.Domain.User", "User")
                        .WithMany("AuthTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.Habit", b =>
                {
                    b.HasOne("LevelHabit.Api.Domain.User", "User")
                        .WithMany("Habits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.HabitCompletion", b =>
                {
                    b.HasOne("LevelHabit.Api.Domain.Habit", "Habit")
                        .WithMany("Completions")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LevelHabit.Api.Domain.User", "User")
                        .WithMany("HabitCompletions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.HabitReminder", b =>
                {
                    b.HasOne("LevelHabit.Api.Domain.Habit", "Habit")
                        .WithOne("Reminder")
                        .HasForeignKey("LevelHabit.Api.Domain.HabitReminder", "HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LevelHabit.Api.Domain.User", "User")
                        .WithMany("HabitReminders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.Notification", b =>
                {
                    b.HasOne("LevelHabit.Api.Domain.Habit", "Habit")
                        .WithMany("Notifications")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LevelHabit.Api.Domain.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.ProgressProfile", b =>
                {
                    b.HasOne("LevelHabit.Api.Domain.User", "User")
                        .WithOne("ProgressProfile")
                        .HasForeignKey("LevelHabit.Api.Domain.ProgressProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.RefreshToken", b =>
                {
                    b.HasOne("LevelHabit.Api.Domain.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.UserAchievement", b =>
                {
                    b.HasOne("LevelHabit.Api.Domain.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LevelHabit.Api.Domain.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.Habit", b =>
                {
                    b.Navigation("Completions");

                    b.Navigation("Notifications");

                    b.Navigation("Reminder");
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.User", b =>
                {
                    b.Navigation("AuthTokens");

                    b.Navigation("HabitCompletions");

                    b.Navigation("HabitReminders");

                    b.Navigation("Habits");

                    b.Navigation("Notifications");

                    b.Navigation("ProgressProfile");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserAchievements");
                });
#pragma warning restore 612, 618
        }
    }
}
