// <auto-generated />
using System;
using LevelHabit.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LevelHabit.Api.Migrations
{
    [DbContext(typeof(LevelHabitDbContext))]
    [Migration("20260619132945_AddAchievements")]
    partial class AddAchievements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LevelHabit.Api.Domain.Achievement", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("rule");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("Target")
                        .HasColumnType("integer")
                        .HasColumnName("target");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.HasKey("Key");

                    b.HasIndex("SortOrder");

                    b.ToTable("achievements", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "first-step",
                            Description = "Complete your first quest.",
                            Rule = "total-completions",
                            SortOrder = 10,
                            Target = 1,
                            Title = "First Step"
                        },
                        new
                        {
                            Key = "getting-started",
                            Description = "Complete 5 quests total.",
                            Rule = "total-completions",
                            SortOrder = 20,
                            Target = 5,
                            Title = "Getting Started"
                        },
                        new
                        {
                            Key = "dedicated",
                            Description = "Complete 25 quests total.",
                            Rule = "total-completions",
                            SortOrder = 30,
                            Target = 25,
                            Title = "Dedicated"
                        },
                        new
                        {
                            Key = "level-up",
                            Description = "Reach hero level 2.",
                            Rule = "level",
                            SortOrder = 40,
                            Target = 2,
                            Title = "Level Up"
                        },
                        new
                        {
                            Key = "hero-rising",
                            Description = "Reach hero level 5.",
                            Rule = "level",
                            SortOrder = 50,
                            Target = 5,
                            Title = "Hero Rising"
                        },
                        new
                        {
                            Key = "on-fire",
                            Description = "Reach a 3-day streak on any quest.",
                            Rule = "best-quest-streak",
                            SortOrder = 60,
                            Target = 3,
                            Title = "On Fire"
                        },
                        new
                        {
                            Key = "unstoppable",
                            Description = "Reach a 7-day streak on any quest.",
                            Rule = "best-quest-streak",
                            SortOrder = 70,
                            Target = 7,
                            Title = "Unstoppable"
                        },
                        new
                        {
                            Key = "hard-mode",
                            Description = "Complete a hard quest.",
                            Rule = "hard-completion",
                            SortOrder = 80,
                            Target = 1,
                            Title = "Hard Mode"
                        },
                        new
                        {
                            Key = "balanced-hero",
                            Description = "Complete quests in at least 3 different categories.",
                            Rule = "completed-categories",
                            SortOrder = 90,
                            Target = 3,
                            Title = "Balanced Hero"
                        });
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.HeroProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer")
                        .HasColumnName("current_streak");

                    b.Property<string>("HeroName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("hero_name");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("TotalXp")
                        .HasColumnType("integer")
                        .HasColumnName("total_xp");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("hero_profiles", (string)null);
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("frequency");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsArchived");

                    b.ToTable("quests", (string)null);
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.QuestCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateOnly>("CompletionDateUtc")
                        .HasColumnType("date")
                        .HasColumnName("completion_date_utc");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("quest_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("XpAwarded")
                        .HasColumnType("integer")
                        .HasColumnName("xp_awarded");

                    b.HasKey("Id");

                    b.HasIndex("QuestId");

                    b.HasIndex("UserId", "QuestId", "CompletionDateUtc")
                        .IsUnique();

                    b.ToTable("quest_completions", (string)null);
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.UserAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AchievementKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("achievement_key");

                    b.Property<DateTimeOffset>("UnlockedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AchievementKey");

                    b.HasIndex("UserId", "AchievementKey")
                        .IsUnique();

                    b.ToTable("user_achievements", (string)null);
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.HeroProfile", b =>
                {
                    b.HasOne("LevelHabit.Api.Domain.User", "User")
                        .WithOne("HeroProfile")
                        .HasForeignKey("LevelHabit.Api.Domain.HeroProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.Quest", b =>
                {
                    b.HasOne("LevelHabit.Api.Domain.User", "User")
                        .WithMany("Quests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.QuestCompletion", b =>
                {
                    b.HasOne("LevelHabit.Api.Domain.Quest", "Quest")
                        .WithMany("Completions")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LevelHabit.Api.Domain.User", "User")
                        .WithMany("QuestCompletions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.UserAchievement", b =>
                {
                    b.HasOne("LevelHabit.Api.Domain.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LevelHabit.Api.Domain.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.Quest", b =>
                {
                    b.Navigation("Completions");
                });

            modelBuilder.Entity("LevelHabit.Api.Domain.User", b =>
                {
                    b.Navigation("HeroProfile");

                    b.Navigation("QuestCompletions");

                    b.Navigation("Quests");

                    b.Navigation("UserAchievements");
                });
#pragma warning restore 612, 618
        }
    }
}
